docs_dir: docs/book
site_dir: docs/html
nav:
    - Home: index.md
    - v3:
        - Introduction: v3/intro.md
        - Reference:
            - "XML-RPC Clients": v3/client.md
            - "XML-RPC Servers": v3/server.md
        - Migration:
            - "Migration to version 3": v3/migration.md
    - v2:
        - Introduction: v2/intro.md
        - Reference:
            - "XML-RPC Clients": v2/client.md
            - "XML-RPC Servers": v2/server.md
site_name: laminas-xmlrpc
site_description: "Fully-featured XML-RPC server and client implementations"
repo_url: 'https://github.com/laminas/laminas-xmlrpc'
extra:
    project: Components
    current_version: v3
    versions:
        - v3
        - v2
plugins:
    redirects:
        redirect_maps:
            intro.md: v3/intro.md
            client.md: v3/client.md
            server.md: v3/server.md
